### ISSUE TITLE
Upgrade Tekton to newer version

### ISSUE THREAD

**Issue by emirgens** [equinor/tekton-helm-chart#1]
Current version of Tekton is 0.44

Find procedure on how to upgrade Tekton

(Test this before release, maby include testing of init contain running as root)

**Comment by Richard87** [comment]
# Tekton 0.53 LTS:

> 🎉 CEL-based when expressions, Results from Matrices, beta promotions and more 🎉
> ## Upgrade Notices
> [TEP-0104] Task-level Resource Requirements in now beta
> Matrix is now beta
> Starting with this release, all new API driven features will be controlled by individual feature flags, and the enable-api-fields flag will be eventually phased out, once all API features currently in alpha/beta reach stability (or are removed)
>
> ## Backwards incompatible changes
> In the current release:
> 
> 🚨 The behaviour of the enable-api-field flag has been fixed, resulting in a slight behaviour change: when using the v1beta1 API, API features in beta are only available when the enable-api-field is set to beta or alpha. Beta features used to be enabled on the v1beta1 API regardless of the value of enable-api-field.
> Note that:
> 
> The default value for enable-api-field is beta
> Users that have the flag set to alpha or beta will continue to have access to beta features on v1beta1 and v1 APIs
> Users that have the flag set to stable will continue to not have access to beta features on the v1 API
> So in practice, there is no breaking change for users. Users of the v1beta1 API may now disable beta features, should they wish to do so, which was not possible before.

# Tekton 0.52:

> No breaking changes 

# Tekton 0.51:

> ## Upgrade Notices
> With this release, the minimun Kubernetes version supported is now 1.25.
> 
> Deprecation Notices
> 🚨 Mark disable-affinity-assistant as deprecated ([#6991](https://github.com/tektoncd/pipeline/pull/6991))
> The disable-affinity-assistant feature flag is deprecated in favour of the new coschedule feature flag. The disable-affinity-assistant feature flag will be removed in 9 months.

# Tekton 0.50:
> 🎉 v1beta1 deprecation (1 year support still) 🎉


# Tekton 0.49:

> ## Backwards incompatible changes
> In current release:
> 
> 🚨 Enable beta features by default ([#6732](https://github.com/tektoncd/pipeline/pull/6732))
> action required: "enable-api-fields" is set to "beta" by default. If you are using v1 APIs and would like to use only stable features, modify the "feature-flags" configmap in the "tekton-pipelines" namespace to set "enable-api-fields" to "stable". Example command: kubectl patch cm feature-flags -n tekton-pipelines -p '{"data":{"enable-api-fields":"stable"}}'
> If you are using v1beta1 APIs, no action is needed.

# Tekton 0.48:
> No breaking changes

# Tekton 0.47 LTS:

> ## Upgrade Notices
> Tekton v0.47 requires Kubernetes 1.24 or newer
> 
> v1alpha1.Run objects are no longer supported. You must upgrade to v1beta1.CustomRun before upgrading to this release. See https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1.Run-to-v1beta1.CustomRun.md for migration instructions
> 
> Feature flag custom-task-version has been removed, tekton pipeline will stop supporting v1alpha1.Run and only use v1beta1.CustomRun.
> 
> for trusted resources users, please change feature flag resource-verification-mode to trusted-resources-verification-no-match-policy, please refer to https://github.com/tektoncd/pipeline/blob/main/docs/trusted-resources.md#enable-trusted-resources to learn how to config the new trusted-resources-verification-no-match-policy feature flag

# Tekton 0.46:

> ## Backwards incompatible changes
> In current release:
> 
> 🚨 remove config-trusted-resources ([#6305](https://github.com/tektoncd/pipeline/pull/6305))
> BREAKING CHANGE: [alpha] config-trusted-resources is removed, please refer to https://github.com/tektoncd/pipeline/blob/main/docs/trusted-resources.md for migrating public keys in VerificationPolicy

# Tekton 0.45:

> ## Action Required
> Please migrate off of pullrequests pipelineresources as it is removed, please refer to the doc at https://github.com/tektoncd/pipeline/blob/main/docs/pipelineresources.md#replacing-an-pullrequest-resource
> Backwards incompatible changes
> In current release:
> 
> 🚨 pipelinerun.status.taskRuns and pipelinerun.status.runs have been removed.
> The pipelinerun.status.taskRuns and pipelinerun.status.runs fields have been removed, along with the embedded-status feature flag. If you are using these fields in your own tooling, please migrate to using pipelinerun.status.childReferences instead. ([#6099](https://github.com/tektoncd/pipeline/pull/6099)).

**Comment by Richard87** [comment]
# Upgrade dependencies:

- [x] https://github.com/equinor/radix-tekton/pull/92 - Merged to main
- [x] https://github.com/equinor/radix-api/pull/557 - Merged to main
- [x] https://github.com/equinor/tekton-helm-chart/pull/4
- [x] https://github.com/equinor/radix-flux/pull/1678 Upgrade Tekton in DEV cluster
- [x] https://github.com/equinor/radix-tekton/pull/93 Merge to release
- [x] https://github.com/equinor/radix-api/pull/558 Merged to release
- [x] https://github.com/equinor/radix-flux/pull/1682 in Playground cluster
- [x] https://github.com/equinor/radix-flux/pull/1683 Tekton in Prod+C2 cluster
